Write to socket only if it is open
cypress-io/node-http-proxy pull request #1
Opened 2021-07-13 11:25 UTC by cardil

Partially fixes cypress-io/cypress#17288

This patch ensures that we write to a socket that is, in fact, open. This prevents exceptions from being thrown, like evidenced in cypress-io/cypress#17288.

2021-12-08 10:14 UTC, cardil commented
/cc @flotwig

2021-12-08 15:27 UTC, flotwig requested changes
Hey @cardil thanks for opening this. Sorry that this flew under the radar. We're working on improving our issue management processes on the team so this happens less often.

Can you please go ahead and create a PR to the `cypress-io/cypress` repo that points `http-proxy` to `cardil/node-http-proxy#eec6ed5f0d65d34faf8bf90a1727764ebc334e81`? That way we can run this change with the existing proxy tests.

`packages/server/test/integration/websockets_spec.js` is an excellent place to add a test for this. cypress-io/cypress#6945 should have had tests but didn't, because I wasn't sure what steps could reproduce this. These tests can be run via `yarn test-integration websockets` inside of `packages/server`

If the PR to `cypress-io/cypress` is passing, then this LGTM.

2021-12-09 10:50 UTC, cardil commented
I'm not sure either what setup would be necessary to reproduce conditions in which the error occurs.

What I can assure that this change helps. After applying openshift-knative/serverless-operator#1099, we've stopped seeing the `Error: This socket has been ended by the other party` on our project.

2021-12-10 21:48 UTC, flotwig commented
@cardil having a PR in `cypress-io/cypress` to point to this branch would let us know if this affects any of the existing websocket tests that we have in that repo before cutting a new release of `@cypress/http-proxy` that may break the actual `cypress` tests.

> I'm not sure either what setup would be necessary to reproduce conditions in which the error occurs.

I'll try to add tests to your PR there if it doesn't break any of the CI in that repo, but if it ends up being a rabbithole, we can get this merged without it.

2024-01-11 22:16 UTC, nanek commented
Thanks @cardil for this fix! I can also confirm after manually applying this change, I have stopped seeing `Error: This socket has been ended by the other party` in cypress.

2024-01-12 05:55 UTC, akshaygupta5233 commented
Hi @nanek . Need your help in setting this up,

2024-05-01 17:43 UTC, JamesNimlos commented
This is still an issue so I went ahead and made a PR to the main Cypress repository to validate this doesn't break existing proxy workflows here: https://github.com/cypress-io/cypress/pull/29453

2024-05-02 15:11 UTC, jennifer-shehane commented
@JamesNimlos Thanks, we'll take a new look at this again.

2024-05-09 18:33 UTC, AtofStryker commented
closing in favor of https://github.com/cypress-io/cypress/pull/29499

2024-05-09 18:33 UTC, closed without merging